### ISSUE TITLE
remove laminas/laminas-db integration

### ISSUE THREAD

**Issue by arhimede** [dotkernel/api#108]
from Oauth

**Comment by bidi47** [comment]
it doesn't look like laminas/laminas-db can be removed
it's classes are used by other packages (laminas-paginator, laminas-validator) even if not required explicitly 
execution crashes if the package is removed

**Comment by arhimede** [comment]
laminas-paginator, laminas-validator are used somewhere ?

**Comment by bidi47** [comment]
laminas-paginator can't be removed from composer.json 
it's only in require-dev for mezzio/mezzio-hal, but crashes if removed

laminas-validator is required by
laminas/laminas-http
laminas/laminas-inputfilter
laminas/laminas-log (require-dev)
laminas/laminas-mail
laminas/laminas-uri
