### ISSUE TITLE
clean composer.json from useless or double packages

### ISSUE THREAD

**Issue by arhimede** [dotkernel/api#109]
all libraries required by composer.json removed if there are already called by another package

**Comment by bidi47** [comment]
@arhimede, please add me to the contributors so i can push the update

i found these packages that can be removed
"laminas/laminas-dependency-plugin": "^2.2"
"laminas/laminas-diactoros": "^2.8"
"laminas/laminas-servicemanager": "^3.10"
"mezzio/mezzio-helpers": "^5.7"

**Comment by bidi47** [comment]
updated composer
some of the packages are updated to use the more recent version
