### ISSUE TITLE
[Insight] The dependencies of your project could not be installed

### ISSUE THREAD

**Issue by arhimede** [dotkernel/api#114]
> SymfonyInsight was not able to install your Composer dependencies. If you need to customize files or run commands to make it work, you can edit your SymfonyInsight project configuration to override the default "pre_composer_script" and/or "post_composer_script" settings.

```
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
In Laminas\DependencyPlugin\DependencyRewriterV2::onPrePoolCreate
Nothing to install, update or remove
Generating optimized autoload files
110 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
PHP CodeSniffer Config installed_paths set to ../../laminas/laminas-coding-standard/src,../../slevomat/coding-standard,../../webimpress,../../webimpress/coding-standard/src
> laminas-development-mode enable

Parse error: syntax error, unexpected &#039;static&#039; (T_STATIC) in /app/vendor/symfony/console/Command/Command.php on line 345

Script laminas-development-mode enable handling the development-enable event returned with error code 255
Script @development-enable was called via post-install-cmd

```

---------------------

_Posted from [SymfonyInsight](https://insight.symfony.com/projects/7f9143cc-5e3c-4cfc-992c-377a001fde3e/analyses/16)_

**Comment by alexmerlin** [comment]
What version of PHP does this tool use?
There's a similar issue discussed [here](https://github.com/zfcampus/zf-development-mode/issues/30) that suggestes that the tool might use an older version of PHP.
