### ISSUE TITLE
Fresh installation broken

### ISSUE THREAD

**Issue by alexmerlin** [dotkernel/api#117]
Upon running a fresh installation of the project, accessing the home page from a browser throws the following error:

> Service with name "dot-mail.service.default" could not be created. Reason: cannot connect to host; error = stream_socket_client(): Unable to connect to tcp://:143 (No connection could be made because the target machine actively refused it) (errno = 0 )

Tested on:
* OS: Windows 11, Ubuntu 20.04 and MacOS Mojave
* PHP: versions 7.4 and 8.1

**Comment by bidi47** [comment]
fixed in https://github.com/dotkernel/dot-mail/pull/38, https://github.com/dotkernel/dot-mail/pull/36, https://github.com/dotkernel/dot-mail/pull/41
