### ISSUE TITLE
remove laminas/laminas-dependency-plugin from composer

### ISSUE THREAD

**Issue by arhimede** [dotkernel/api#123]
remove any mention of 
laminas/laminas-dependency-plugin

**Comment by alexmerlin** [comment]
@arhimede @MarioRadu Is this issue still relevant?
I see that DK Frontend and DK Admin still allow `laminas/laminas-dependency-plugin` in their **composer.json** files.

**Comment by arhimede** [comment]
@alexmerlin  we want to remove completely from everywhere the `laminas/laminas-dependency-plugin` mention

https://github.com/orgs/dotkernel/projects/4. 
Please list there in that project all ***dot-*** packages which require laminas-dependcy plugin and modify it one by one

**Comment by alexmerlin** [comment]
Fixed in #191
