### ISSUE TITLE
Error report endpoint

### ISSUE THREAD

**Issue by marioradu05** [dotkernel/api#146]
The error report endpoint is not protected in any way, anyone can spam it with junk, junk that will be saved in log files.

@arhimede do we need this endpoint ? and why ?

**Comment by arhimede** [comment]
@kakapiciu  Please write an explanatory article about that 
in dotkernel.com

**Comment by alexmerlin** [comment]
@arhimede Continuing on @MarioRadu's questions, we could at least add a domain whitelist to this feature.
For example, in **config/autoload/error-handling.global.php**, under the `error-report` key, we could add a new configuration - `domain_whitelist` - where developers can store an array of domains that are allowed to write logs by calling this endpoint.

**Comment by arhimede** [comment]
Agree

Domains or ips or both

**Comment by arhimede** [comment]
Please add a whitelist feature based on a token too 

In case that the user is using a mobile app

**Comment by alexmerlin** [comment]
> Please add a whitelist feature based on a token too
> 
> In case that the user is using a mobile app

@arhimede and @MarioRadu:
If we implement token-based access to this feature, should we still keep the domain/IP whitelists?
I find using tokens way more practical than using whitelists and I expect most apps to use only tokens.

**Comment by alexmerlin** [comment]
Fixed in #178 and #182
