### ISSUE TITLE
remove PHP 7.4 support after mezzio 3.12 in API V4

### ISSUE THREAD

**Issue by arhimede** [dotkernel/api#153]
composer.json
"php": "~7.4.0 || ~8.0.0 || ~8.1.0", -> "php": "~8.0.0 || ~8.1.0 || ~8.2.0",

"mezzio/mezzio": "^3.11.0", -> "mezzio/mezzio": "^3.13.0",

**Comment by marioradu05** [comment]
Done in https://github.com/dotkernel/api/pull/163.
