### ISSUE TITLE
PHP 8.2 installation

### ISSUE THREAD

**Issue by tasselchof** [dotkernel/api#194]
Hello!

I see that some components are require PHP up to 8.1:
- dotkernel/dot-response-header 3.1.0 requires php ~7.4.0 || ~8.0.0 || ~8.1.0 -> your php version (8.2.3) does not satisfy that requirement.
- dotkernel/dot-errorhandler[3.2.0, ..., 3.2.1] require php ~7.4.0 || ~8.0.0 || ~8.1.0 -> your php version (8.2.3) does not satisfy that requirement.

Maybe it makes sense to allow them to run on 8.2?

**Comment by alexmerlin** [comment]
Hey Maxim, thanks for contacting us!

We are currently updating all our active packages to support PHP 8.2; most of them being already updated.
Once all finished in a couple of days, you can use their latest versions in your projects.

**Comment by alexmerlin** [comment]
Hey @tasselchof 
The process of updating both DotKernel API and our packages has finished.
You can now install/update your DotKernel API project.

Feel free to report issues if you encounter any.

**Comment by tasselchof** [comment]
No issues so far, thanks! =)
