### ISSUE TITLE
new badges

### ISSUE THREAD

**Issue by arhimede** [dotkernel/api#216]
see which ones worth the effort to be implemented 

https://github.com/chubbyphp/chubbyphp-framework

**Comment by alexmerlin** [comment]
### See below the available badges:

Reliability Rating
[![Reliability Rating](https://sonarcloud.io/api/project_badges/measure?project=dotkernel_api&metric=reliability_rating)](https://sonarcloud.io/summary/new_code?id=dotkernel_api)

Quality Gate Status
[![Quality Gate Status](https://sonarcloud.io/api/project_badges/measure?project=dotkernel_api&metric=alert_status)](https://sonarcloud.io/summary/new_code?id=dotkernel_api)

Technical Debt
[![Technical Debt](https://sonarcloud.io/api/project_badges/measure?project=dotkernel_api&metric=sqale_index)](https://sonarcloud.io/summary/new_code?id=dotkernel_api)

Coverage (needs additional setup)
[![Coverage](https://sonarcloud.io/api/project_badges/measure?project=dotkernel_api&metric=coverage)](https://sonarcloud.io/summary/new_code?id=dotkernel_api)

Lines of Code
[![Lines of Code](https://sonarcloud.io/api/project_badges/measure?project=dotkernel_api&metric=ncloc)](https://sonarcloud.io/summary/new_code?id=dotkernel_api)

Code Smells
[![Code Smells](https://sonarcloud.io/api/project_badges/measure?project=dotkernel_api&metric=code_smells)](https://sonarcloud.io/summary/new_code?id=dotkernel_api)

Maintainability Rating
[![Maintainability Rating](https://sonarcloud.io/api/project_badges/measure?project=dotkernel_api&metric=sqale_rating)](https://sonarcloud.io/summary/new_code?id=dotkernel_api)

Security Rating
[![Security Rating](https://sonarcloud.io/api/project_badges/measure?project=dotkernel_api&metric=security_rating)](https://sonarcloud.io/summary/new_code?id=dotkernel_api)

Bugs
[![Bugs](https://sonarcloud.io/api/project_badges/measure?project=dotkernel_api&metric=bugs)](https://sonarcloud.io/summary/new_code?id=dotkernel_api)

Vulnerabilities
[![Vulnerabilities](https://sonarcloud.io/api/project_badges/measure?project=dotkernel_api&metric=vulnerabilities)](https://sonarcloud.io/summary/new_code?id=dotkernel_api)

Duplicated Lines
[![Duplicated Lines (%)](https://sonarcloud.io/api/project_badges/measure?project=dotkernel_api&metric=duplicated_lines_density)](https://sonarcloud.io/summary/new_code?id=dotkernel_api)

Quality Gate
[![Quality gate](https://sonarcloud.io/api/project_badges/quality_gate?project=dotkernel_api)](https://sonarcloud.io/summary/new_code?id=dotkernel_api)

Advertise the usage of SonarCloud
[![SonarCloud](https://sonarcloud.io/images/project_badges/sonarcloud-white.svg)](https://sonarcloud.io/summary/new_code?id=dotkernel_api) [![SonarCloud](https://sonarcloud.io/images/project_badges/sonarcloud-black.svg)](https://sonarcloud.io/summary/new_code?id=dotkernel_api) [![SonarCloud](https://sonarcloud.io/images/project_badges/sonarcloud-orange.svg)](https://sonarcloud.io/summary/new_code?id=dotkernel_api)

### I would recommend using the ones related to code quality and security:
* Reliability Rating
* Coverage
* Code Smells
* Security Rating
* Bugs
* Vulnerabilities
