### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by bidi47** [dotkernel/api#228]

**Comment by arhimede** [comment]
tutorials section:
  - how to create a "products" endpoint 
  - how to TBD
 Requirements,

**Comment by arhimede** [comment]
![image](https://github.com/dotkernel/api/assets/22009710/0c129bee-5028-4646-930a-b6e3c0086d1c)

**Comment by arhimede** [comment]
https://api-tools.getlaminas.org/documentation

**Comment by arhimede** [comment]
add also a page like: 
- From development to production 
    composer dev , versus no-dev

**Comment by alexmerlin** [comment]
Fixed in https://github.com/dotkernel/api/pull/238
