### ISSUE TITLE
dotkernel/dot-data-fixtures not updated

### ISSUE THREAD

**Issue by arhimede** [dotkernel/api#241]
currently in compsoer.json we have 
 "dotkernel/dot-data-fixtures": "^1.1.3",

but does not want to upgrade to 1.2.0 for some reason

**Comment by bidi47** [comment]
the update is restricted by require symfony/console: ^5.1
currently symfony/console: v7.0.3 is installed in frontend (required by laminas/laminas-cli and vimeo/psalm)
we should see if v7 works on dotkernel/dot-data-fixtures
note: symfony/console: v6 might also be allowed, if v7 causes issues

**Comment by alexmerlin** [comment]
See https://github.com/dotkernel/dot-data-fixtures/issues/19
Fixed in https://github.com/dotkernel/dot-data-fixtures/pull/20
