### ISSUE TITLE
add 3 new pages to documentation: flow schemes

### ISSUE THREAD

**Issue by arhimede** [dotkernel/api#244]
https://www.dotkernel.org/page/flowLibraries
https://www.dotkernel.org/page/flowMiddlewares
https://www.dotkernel.org/page/flowLibrariesEmail

**Comment by bidi47** [comment]
attached images from dotkernel-org
@arhimede, @alexmerlin, where should I add these images?

![dotkernel-library-flow](https://github.com/dotkernel/api/assets/27284979/be9d72ae-dea2-4285-91cb-1ad23c967154)
![dotkernel-library-flow-email](https://github.com/dotkernel/api/assets/27284979/83caba7c-b987-4e7d-89dd-3993f553e2b3)
![dotkernel-middleware-flow](https://github.com/dotkernel/api/assets/27284979/2f8d188f-f279-427e-8e8b-217b63f8789c)

**Comment by arhimede** [comment]
@MarioRadu  please create 3 new pages in documentation, 
Separate menu items, like "Introduction" and "Tutorials"
called "Flows" ( maybe ) 
and one page for each of the above graph

**Comment by arhimede** [comment]
@bidi47 please upload the 3 files here 
https://github.com/dotkernel/dotkernel.github.io/tree/main/img/api

**Comment by bidi47** [comment]
i uploaded the 3 pngs
