### ISSUE TITLE
Documentation test 

### ISSUE THREAD

**Issue by arhimede** [dotkernel/api#249]
in this page 
https://github.com/dotkernel/api/blob/4.0/docs/book/v4/introduction/getting-started.md
the below command is valid ?
with that . ( dot) ?

```
git clone https://github.com/dotkernel/api.git .
```

**Comment by alexmerlin** [comment]
Yes, it instructs Git to clone the repository in the current directory.

**Comment by alexmerlin** [comment]
One thing that we should improve is to either use the current directory as instructed [here](http://docs.dotkernel.org/api/) or a new directory, like [here](http://docs.dotkernel.org/api/v4/introduction/getting-started/).
The first one page uses `.` as it was our quick fix from last week, which replaced the Composer command.
