### ISSUE TITLE
Content negociation implementation

### ISSUE THREAD

**Issue by arhimede** [dotkernel/api#259]
https://api-tools.getlaminas.org/documentation/api-primer/content-negotiation

let's talk about that

**Comment by arhimede** [comment]
https://github.com/laminas-api-tools/api-tools-content-negotiation

**Comment by marioradu05** [comment]
Middleware after the `RouteMiddleware` to check the content negociation rules from a config file.

**Comment by arhimede** [comment]
when the Accept header is missing 

"ERR","message":"trim(): Argument #1 ($string) must be of type string, false given","extra":{"\u0000*\u0000message":"trim(): Argument #1 ($string) must be of type string, false given","\u0000Error\u0000string":"","\u0000*\u0000code":0,"\u0000*\u0000file":"/var/www/vhosts/api.dotkernel.net/httpdocs/src/App/src/Middleware/ContentNegotiationMiddleware.php",

**Comment by bidi47** [comment]
https://docs.dotkernel.org/api-documentation/v5/core-features/content-validation/
