### ISSUE TITLE
article and instructions for content-negotiation

### ISSUE THREAD

**Issue by arhimede** [dotkernel/api#267]
article on dotkernel.com 

+ documentation page in docs

**Comment by bidi47** [comment]
https://docs.dotkernel.org/api-documentation/v5/core-features/content-validation/

**Comment by arhimede** [comment]
@bidi47 we need an article too on dotkernel.com

**Comment by arhimede** [comment]
@bidi47  did it !!

**Comment by bidi47** [comment]
https://www.dotkernel.com/dotkernel-api/content-negotiation-in-dotkernel-rest-api
