### ISSUE TITLE
extend the return of control api call

### ISSUE THREAD

**Issue by arhimede** [dotkernel/api#270]
the call to api.dotkernel.net

can return something like 

```php

``` {"message":"Welcome to Dotkernel API!","debug":{"database":"connected","php":"6.4.28"}}

**Comment by alexmerlin** [comment]
Shouldn't this rather be a separate endpoint? Like `/status` or `/health-check`?

Easter egg noticed...

**Comment by arhimede** [comment]
can be a separate endpoint , maybe 

- if will be an open endpoint, ( no token required) then can stay in the main/current  endpoint 
   and return **public** and harmless informations:
  The purpose would be to quickly indicate that after an upgrade, composer update, regenerate cache , etc. operation the APi is still up 
PHP version will be returned from the x-powered-by header, not from php info   

-  if will be a protected endpoint, with token required, then it can return some debug infos , like :
   what we have now in dot-debugbar, at **Request** and **Config** tabs
