### ISSUE TITLE
dot-attributed-services package

### ISSUE THREAD

**Issue by arhimede** [dotkernel/api#274]
to be done in order to implement attributes in version 5

**Comment by alexmerlin** [comment]
Late idea:
Maybe we could use the opportunity to lose the `dot-*-services` pattern and call this package `dot-dependency-injections`, making clear for anyone what this package does?

**Comment by arhimede** [comment]
I agree

**Comment by arhimede** [comment]
@cPintiuta  a new library was created
in case we want to use this one 

as half of the internet confuse the word attributes with annotation and vice-versa

**Comment by arhimede** [comment]
fixed with the release of https://github.com/dotkernel/dot-dependency-injection package
