### ISSUE TITLE
how to generate a token ?

### ISSUE THREAD

**Issue by arhimede** [dotkernel/api#276]
If I want to generate a token to do various API calls, 
how should I do it ?

The below page is not useful 
https://github.com/dotkernel/api/blob/5.0/documentation/command/token-generate.md

**Comment by alexmerlin** [comment]
This command is NOT for generating access tokens. It can be extended to that as well, but in its current form, it cannot only 
generate tokens for the error-reporting endpoint (used by JS frontends to report various errors to the API).

---

If you want to generate an access token, you can do that using `Postman` (or `curl` if you don't have Postman installed).

**Comment by arhimede** [comment]
How ? 
Lets xomplete the documentation about that ...

**Comment by alexmerlin** [comment]
We have an article about working with Postman.
https://www.dotkernel.com/how-to/postman-for-documentation-in-dotkernel-api-3/

Once the documentation files described in the article are imported, you can generate/refresh access tokens and send requests to the endpoints.

I'll create a new page in the API documentation on the entire flow.

**Comment by alexmerlin** [comment]
Documentation for token authentication is here:
https://docs.dotkernel.org/api-documentation/v4/tutorials/token-authentication/
