### ISSUE TITLE
Remove doctrine/orm after roave update

### ISSUE THREAD

**Issue by pinclau** [dotkernel/api#286]
We currently put doctrine/orm in composer to ensure minimum version of 3.2.
Currently  roave/psr-container-doctrine request a minimum v 3.0, and that version has some bugs. 
If roave/psr-container-doctrine updates to a minimum doctrine/orm 3.2, we can remove it from composer

**Comment by arhimede** [comment]
https://github.com/Roave/psr-container-doctrine version 5.2 is about to be released, and require orm 3.2
