### ISSUE TITLE
protect /documentation if its browser call

### ISSUE THREAD

**Issue by kakapiciu** [dotkernel/api#29]

**Comment by arhimede** [comment]
decision: either remove it from repo, or do something

**Comment by arhimede** [comment]
If we move from composer.json swagger to dev, what happens ?

**Comment by kakapiciu** [comment]
nothing....documentation/index.php is using documentation/css/swagger-ui.css and documentation/js/swagger-ui-bundle.js + documentation/js/swagger-ui-standalone-preset.js...u can easily remove it from composer.json

**Comment by alexmerlin** [comment]
As per this [PR](https://github.com/dotkernel/api/pull/63) DotKernel API's /documentation will be replaced with a different library.
