### ISSUE TITLE
invalid schema

### ISSUE THREAD

**Issue by arhimede** [dotkernel/api#293]
`php bin/doctrine orm:validate-schema`

returns:

PHP Fatal error:  Cannot declare class Api\User\Entity\UserAvatar, because the name is already in use in /var/www/vhosts/api.dotkernel.net/httpdocs/src/User/src/Entity/UserAvatar.php on line 17

**Comment by alexmerlin** [comment]
It seems to be working fine.

```shell
php bin/doctrine orm:validate-schema
```

```text
Mapping
-------

[OK] The mapping files are correct.

Database
--------

[OK] The database schema is in sync with the mapping files.
```

Did you try clearing Doctrine cache?
```shell
sudo rm -rf data/cache/doctrine/ data/cache/DoctrineEntityProxy/
```

**Comment by arhimede** [comment]
online on api.dotkernel.net is still the error
clean cache 
or no cache

**Comment by arhimede** [comment]
PHP Fatal error:  Cannot declare class Api\User\Entity\UserRole, because the name is already in use in /var/www/vhosts/api.dotkernel.net/httpdocs/src/User/src/Entity/Api/User/Entity/UserRole.php on line 8
