### ISSUE TITLE
Replace Psalm with PHPStan ?

### ISSUE THREAD

**Issue by arhimede** [dotkernel/api#324]
"use one static analysis tool and Doctrine projects will use PHPStan going forward. For now Psalm checks will be removed from repositories over the next weeks.

This is mainly because PHPStan has outpaced Psalm in depth and quality in the last few years and it feels unlikely that Psalm can point to a problem that PHPStan did not detect before. If in the future Psalm catches up to PHPStan we may reconsider adding it."

**Comment by arhimede** [comment]
@MarioRadu  maybe we will need to create a separate library 
phpstan-mezzio 
to handle custom mezzio logic

**Comment by arhimede** [comment]
example:
https://github.com/Slamdunk/phpstan-laminas-framework

**Comment by arhimede** [comment]
https://github.com/phpstan/phpstan/discussions/8986

**Comment by arhimede** [comment]
so the decision of Dotkernel TSC was to swith to phpstan and drop psalm
and create a *.neo files with temporary exceptions

https://github.com/doctrine/orm/blob/3.3.x/phpstan.neon
https://github.com/doctrine/orm/blob/3.3.x/phpstan-params.neon

Level 5 for the moment

**Comment by alexmerlin** [comment]
Implemented in #348 #349 #350 and #351
