### ISSUE TITLE
User Identity route feature for searching users by identity and not uuid

### ISSUE THREAD

**Issue by matthewpallotta** [dotkernel/api#328]
Feature request:
  Ability to also search by user identity to retrieve identity and user details. 
  Ideas
  GET user.identity.view  /user/identity/{identity} 
  GET identity.view /identity/{identity}

**Comment by alexmerlin** [comment]
Hey @matthewpallotta
Thank you for your message, we're glad to see your interest in Dotkernel API.

At the moment, we do not plan on adding such a feature to Dotkernel API, but we can create a short tutorial in the [documentation](https://docs.dotkernel.org/api-documentation/) on how to create such endpoints.

**Comment by matthewpallotta** [comment]
That would be very helpful as I am still learning the system.

**Comment by arhimede** [comment]
@matthewpallotta  we have a tutorial in the API documentation about that .

https://docs.dotkernel.org/api-documentation/v5/tutorials/find-user-by-identity/
