### ISSUE TITLE
Role Not Found

### ISSUE THREAD

**Issue by Digital-Pig-LLC** [dotkernel/api#332]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 5

#### Summary
Trying to create an admin user fails after successful installation of project.

#### Current behavior
php ./bin/cli.php admin:create -i vt_admin -p "*********"

In AdminRoleService.php line 35:

  Role not found.

#### How to reproduce
Could not tell you precisely as I've been working all day to install and get setup with laminas api-tools only to read the blog post about its deprecation.
My install steps were as follows:
- git cloned the project
- pushed it to my spacecode project
- pulled it in as a submodule to my project running in docker
- ran composer install, all was well
- copied and updated configs as needed
- created db schema
- ran migration to populate schema (all ran with no issue)
- ran the admin:create and got the error

I noticed that the admin_role table is empty. I also dumped the param in the above failing file, and the output was:
Array
(
    [name] => admin
)

#### Expected behavior
I would expect it find the admin role in the admin_roles table

#### Resolved by
To solution wasn't difficult, just unexpected so thought I'd mention it.

INSERT INTO admin_role (uuid, name, created, updated)
VALUES (UNHEX(REPLACE(UUID(),'-','')), 'admin', NOW(), NOW());

After that admin:create worked fine.

Thank you.

**Comment by alexmerlin** [comment]
Hey @Digital-Pig-LLC 

Besides the migration, you also need to run the database fixtures, they will create all the entities you need in order to get started with the project.

Check out the [docs on how to run the fixtures](https://docs.dotkernel.org/api-documentation/v5/installation/doctrine-orm/#executing-fixtures).

Feel free to let us know if you encounter any other issue going forward.

**Comment by Digital-Pig-LLC** [comment]
Ah, thank you! Like I mentioned it's been a long day so I totally missed that.
