### ISSUE TITLE
[RFC]:  remove laminas-json

### ISSUE THREAD

**Issue by arhimede** [dotkernel/api#342]
## RFC

| Q                   | A      |
| ------------------- | ------ |
| BC Break?           | Yes|

### Goal

remove [laminas-json](https://github.com/laminas/laminas-json) and replace its functionality with 
`It got some decoratives for objects to json conversions. json is now in php core and it got to json magic method`

in all projects

**Comment by alexmerlin** [comment]
Dotkernel API does not use `laminas/laminas-json`.

---

To confirm, running:
```shell
composer why laminas/laminas-json
```
outputs:
> In BaseDependencyCommand.php line 98:
>
>  Could not find package "laminas/laminas-json" in your project

**Comment by alexmerlin** [comment]
Also, checked all other projects (Admin, Frontend and Light), they do not require `laminas/laminas-json`.

`laminas/laminas-json` is required only by `laminas/laminas-view`, so that will have to be removed on their end.
