### ISSUE TITLE
Nesting tag issue in templates

### ISSUE THREAD

**Issue by bidi47** [dotkernel/api#50]
the <p> tag doesn't accept nesting. remove the < p > tags before the 'Hi' line and the < /p > after it

recover-identity-requested.html.twig
`    <p>
    <p>Hi {{ user.detail.firstname ?? user.getDetail().getEmail() ?? user.getIdentity() }},</p>
    </p>`

reset-password-requested.html.twig
`    <p>
        <p>Hi {{ user.detail.firstname ?? user.identity }},</p>
    </p>`

**Comment by arhimede** [comment]
@Jurj-Bogdan pelase check in admin and in frontend if we have the same issue too
