### ISSUE TITLE
AccountActivateHandler.php POST

### ISSUE THREAD

**Issue by bidi47** [dotkernel/api#51]
the last line has a call for the old location for email. this needs investigating as i can't be sure what the intended result should be

`return $this->infoResponse(sprintf(Message::MAIL_SENT_USER_ACTIVATION, $user->getEmail()));`

the 2nd parameter in sprintf should be either 
$user->getIdentity()
OR
$user->getDetail()->getEmail()

**Comment by alexmerlin** [comment]
@bidi47 As long as user accounts need to (and currently can only) be activated via email, the info message should use `$user->getDetail()->getEmail()`. See [this PR](https://github.com/dotkernel/api/pull/64) for the fix.
