### ISSUE TITLE
Documentation credentials

### ISSUE THREAD

**Issue by marioradu05** [dotkernel/api#52]
The credentials from the /documentation route are not updated to reflect the last changes.

In the documentation for the /oauth2/generate the default credentials are : 

```
{
  "grant_type": "password",
  "client_id": "dotkernel",
  "client_secret": "dotkernel",
  "scope": "api",
  "username": "test@dotkernel.com",
  "password": "dotkernel"
}
```
If we try them it will return a 401 Unauthorized error.

The "client_id" and "client_secret" should be changed to : 

`client_id : frontend`
`client_secret : frontend` 

if we want to login as a regular user, OR : 

`client_id : admin`
`client_secret : admin` 

if we want to login as an admin.

I didn't found the credentials to login as an admin, I only know the username, which is `admin`. Where can I find the password?

**Comment by alexmerlin** [comment]
here: dotadmin

**Comment by arhimede** [comment]
@MarioRadu and @kakapiciu Please clarify this in the documentation ASAP

**Comment by marioradu05** [comment]
This issue was resolved.
