### ISSUE TITLE
RestDispatchTrait method fromObject not used

### ISSUE THREAD

**Issue by marioradu05** [dotkernel/api#53]
The `fromObject` method from `Api\App\RestDispatchTrait` is not used. What is actually used is the `fromObject` method from `Mezzio\Hal\ResourceGenerator`.
We can remove the unused method from the `Api\App\RestDispatchTrait` .

**Comment by alexmerlin** [comment]
@MarioRadu you sure you meant `fromObject`? Because there's no such method in `Api\App\RestDispatchTrait`.
Also checked git history, it never existed.

**Comment by alexmerlin** [comment]
No fix needed.
