### ISSUE TITLE
documentation restart

### ISSUE THREAD

**Issue by arhimede** [dotkernel/api#66]
1. fresh instalare 
   rulesz consola
*** daca nu e compelt, return error cu toate unde nu e complet
 file 
line 
method 
citesc * RouteDelegarot.php !!!!!
 generez fisier html 
  data sus : generat in 12.03.2019 
citeste Frontendu

**Comment by arhimede** [comment]
Let's use POSTMAN 
and export collections from POSTMAN into a folder called 
documentation 
or 
postman 
in a root level folder

**Comment by alexmerlin** [comment]
DotKernel API 3.0 uses Postman collections to manage documentation. See [/documentation](https://github.com/dotkernel/api/tree/3.0/documentation) for more details.
