### ISSUE TITLE
admin register

### ISSUE THREAD

**Issue by alexmerlin** [dotkernel/api#69]
What is the purpose of the `POST /admin` endpoint? (aka `admin:register`)
If we intend to keep it in the API, we better remove authentication completely - so it's easier for unauthorized people to make API calls.

**Comment by arhimede** [comment]
It's an idea to remove authentication completely .... 

But we need a way ( endpoint) to create new admin's

**Comment by alexmerlin** [comment]
we'll have to come up with a smarter method - I'll find something

**Comment by alexmerlin** [comment]
What if we turn this into a CLI command?
I guess the whole idea of `admin:register` was to provide a way into the admin panel if all other admins leave the system and there's no one left to create a new admin account.
A command could solve this problem, as theoretically someone should have access to a terminal in order to execute the command.

**Comment by arhimede** [comment]
To allow creation of admin accounta only using CLI seem a very good idea....

**Comment by alexmerlin** [comment]
On branch [3.0](https://github.com/dotkernel/api/tree/3.0) a new admin can be created using command `admin:create`
